const wordData = [
  { word: "健身", pinyin: "jianshen", meaning: "to work out" },
  { word: "頭痛", pinyin: "toutong", meaning: "headache; to have a headache" },
  { word: "拉肚子", pinyin: "ladùzi", meaning: "to have diarrhea" },
  { word: "看病", pinyin: "kanbing", meaning: "to see a doctor" },
  { word: "老是", pinyin: "laoshi", meaning: "always (negatively)" },
  { word: "改", pinyin: "gai", meaning: "to change; to correct" },
  { word: "健身房", pinyin: "jianshenfang", meaning: "gym" },
  { word: "從小", pinyin: "congxiao", meaning: "since childhood" },
  { word: "操場", pinyin: "caochang", meaning: "sports field; playground" },
  { word: "體育", pinyin: "tiyu", meaning: "physical education; sports" },
  { word: "腿", pinyin: "tui", meaning: "leg" },
  { word: "脖子", pinyin: "bozi", meaning: "neck" },
  { word: "死", pinyin: "si", meaning: "to die (also used for emphasis)" },
  { word: "誇張", pinyin: "kuazhang", meaning: "exaggerated" },
  { word: "叫", pinyin: "jiao", meaning: "to call; to shout" },
  { word: "救護車", pinyin: "jiuhuche", meaning: "ambulance" },
  { word: "送", pinyin: "song", meaning: "to send; to take (someone)" },
  { word: "救命", pinyin: "jiuming", meaning: "help!; to save a life" },
  { word: "照", pinyin: "zhao", meaning: "to take (photo/X-ray)" },
  { word: "教練", pinyin: "jiaolian", meaning: "coach; trainer" },
  { word: "變", pinyin: "bian", meaning: "to change; become" },
  { word: "體重", pinyin: "tizhong", meaning: "body weight" },
  { word: "減", pinyin: "jian", meaning: "to reduce; to lose (weight)" },
  { word: "下", pinyin: "xia", meaning: "to drop; fall" },
  { word: "年紀", pinyin: "nianji", meaning: "age" },
  { word: "男人", pinyin: "nanren", meaning: "man" },
  { word: "女人", pinyin: "nvren", meaning: "woman" },
  { word: "老人", pinyin: "laoren", meaning: "elderly person" },
  { word: "青菜", pinyin: "qingcai", meaning: "vegetable (leafy)" },
  { word: "漢堡", pinyin: "hanbao", meaning: "hamburger" },
  { word: "薯條", pinyin: "shutiao", meaning: "French fries" },
  { word: "餅乾", pinyin: "binggan", meaning: "cookies; crackers" },
  { word: "飲食", pinyin: "yinshi", meaning: "diet; eating habits" },
  { word: "油", pinyin: "you", meaning: "oil" },
  { word: "鹽", pinyin: "yan", meaning: "salt" },
  { word: "可樂", pinyin: "kele", meaning: "cola" },
  { word: "開水", pinyin: "kaishui", meaning: "boiled/plain water" },
  { word: "來不及", pinyin: "laibuji", meaning: "too late; not enough time" },
  { word: "來得及", pinyin: "laideji", meaning: "still have time" },
  { word: "三餐", pinyin: "sancan", meaning: "three meals" },
  { word: "餐", pinyin: "can", meaning: "meal" },
  { word: "國王", pinyin: "guowang", meaning: "king" },
  { word: "到底", pinyin: "daodi", meaning: "exactly; on earth" },
  { word: "活", pinyin: "huo", meaning: "to live" },
  { word: "訓練", pinyin: "xunlian", meaning: "training; to train" },
  { word: "慢跑", pinyin: "manpao", meaning: "to jog; jogging" }
];
